In [61]:
#Importing the required libraries to read,visualize and model the givn dataset files
import pandas as pd
import numpy as nm
import seaborn as sns
import matplotlib.pyplot as mtp
import plotly.graph_objects as go
import plotly.express as px
import missingno as msno 
import warnings
warnings.filterwarnings("ignore")
import re
import string
import nltk
from nltk.corpus import stopwords
from sklearn import model_selection
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.model_selection import RepeatedStratifiedKFold
import nltk
from nltk.tokenize import word_tokenize,RegexpTokenizer
from nltk.stem import WordNetLemmatizer

In [62]:
#load features as x and target labels as y from directory.
x=nm.load("x_data.npy",allow_pickle=True)
y=nm.load("y_data.npy",allow_pickle=True)

In [63]:
#split our data into testing and training sample.
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x , y, test_size= 0.20, random_state=0) 

In [64]:

#Define a function to fit and predict on training and test data sets
def fit_and_predict(model,x_train,y_train,x_test,y_test):
    
    
    # Fitting training sample into model and make predictions using testing sample.
    clf = model
    clf.fit(x_train, y_train)
    predictions=clf.predict(x_test)
    
    
    
    #making report like accuracy score,predictions of ML models.
    print("{}" .format(model))
    print('-'*50)
    print(classification_report(y_test,predictions))
    print('-'*50)
    print('Accuracy of classifier on training set : {}%'.format(round(clf.score(x_train, y_train)*100)))
    print('-'*50)
    print('Accuracy of classifier on  testing set : {}%' .format(round(accuracy_score(y_test,predictions)*100)))
    print('='*70)
    print('='*70)
    return clf

In [65]:
#define a function to get predictions of x.
def get_predictions(model, x_test):
    predictions=model.predict(x_test)
    return predictions

In [66]:
# Create a list of the machine learning  models to be used for classification and regression.
models=[LogisticRegression(C=1.0),DecisionTreeClassifier(),
        RandomForestClassifier(), SVC(kernel='linear', random_state=0)]

In [67]:
# Loop through the list of models and use 'fit_and_predict()' function to trian and make predictions.
prepared_models = []
for model in models:
    prepared_models.append(fit_and_predict(model,x_train, y_train,x_test,y_test))



LogisticRegression()
--------------------------------------------------
              precision    recall  f1-score   support

           0       0.84      1.00      0.92       416
           1       0.74      0.57      0.64        92
           2       0.77      0.84      0.81       160
           3       0.57      0.24      0.34       123

    accuracy                           0.80       791
   macro avg       0.73      0.66      0.68       791
weighted avg       0.77      0.80      0.77       791

--------------------------------------------------
Accuracy of classifier on training set : 80%
--------------------------------------------------
Accuracy of classifier on  testing set : 80%
DecisionTreeClassifier()
--------------------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       416
           1       0.99      1.00      0.99        92
           2       0.98      0.99      0.98       160
        

In [68]:
#Loop through the list of prepared_models and make predictions on testing data.
for i in range(4):

    print(prepared_models[i])
    print('*'*50)
    print(get_predictions(prepared_models[i], x_test))


LogisticRegression()
**************************************************
[0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 0 0 2 0 0 2 0 0 0 0 3 1 0 0 3 3 0 2 0 2 0
 2 2 0 0 0 3 2 2 0 0 0 0 2 0 0 0 0 0 1 3 0 2 0 2 1 0 0 2 0 0 2 0 2 0 0 0 0
 0 0 0 2 1 3 0 2 0 2 1 0 3 0 0 2 2 0 2 0 1 0 2 0 0 0 0 2 0 0 2 1 0 0 0 0 3
 0 0 0 2 1 0 2 2 2 3 0 0 0 0 2 1 3 0 0 2 0 0 3 0 2 0 0 0 0 0 1 0 0 1 0 3 0
 0 2 1 0 0 0 0 2 2 2 0 2 0 0 0 2 0 2 0 1 0 2 0 0 2 2 2 0 3 2 2 1 0 0 1 1 0
 0 0 0 0 3 0 2 3 1 0 0 2 0 0 0 2 1 0 3 0 0 0 0 0 3 0 3 2 2 1 1 0 0 0 0 0 0
 0 2 3 0 0 0 0 0 0 0 0 0 3 0 0 0 0 3 0 1 2 0 0 0 2 0 1 0 0 0 3 0 0 1 0 2 1
 0 3 0 0 0 2 0 2 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 0 1 0 0 0 0 2 0 0 0 2 0 0 3
 0 0 0 0 1 2 3 1 0 0 2 0 0 2 0 0 0 2 0 2 1 3 2 0 2 0 2 0 0 0 0 2 0 0 0 0 0
 0 2 2 2 2 0 0 0 0 0 0 2 2 0 0 0 1 0 2 0 0 0 0 2 0 2 3 0 0 0 2 2 0 0 0 0 2
 2 0 2 0 2 1 0 0 0 1 0 0 0 1 0 2 2 1 0 0 2 0 2 0 0 0 0 0 0 0 0 2 0 0 0 1 2
 0 3 0 0 0 0 2 0 2 0 0 0 2 0 0 0 3 0 2 0 0 2 0 2 0 3 0 0 1 0 0 2 0 0 0 2 0
 2 0 0 0 0 0 0 2 0 0 2 1 1 1

In [69]:
#loop through prepared_models to get confusion matrices of models.
for i in range(4):

    y_pred= prepared_models[i].predict(x_test)  
    from sklearn.metrics import confusion_matrix  
    con_mat = confusion_matrix(y_test, y_pred)

    print('classifier :',prepared_models[i])
    print(50*'=')
    print('confusion matrix :-')
    print(con_mat)
    print(70*'*')

classifier : LogisticRegression()
confusion matrix :-
[[416   0   0   0]
 [ 40  52   0   0]
 [  2   0 135  23]
 [ 35  18  40  30]]
**********************************************************************
classifier : DecisionTreeClassifier()
confusion matrix :-
[[416   0   0   0]
 [  0  92   0   0]
 [  0   0 158   2]
 [  0   1   4 118]]
**********************************************************************
classifier : RandomForestClassifier()
confusion matrix :-
[[416   0   0   0]
 [  0  92   0   0]
 [  0   0 159   1]
 [  0   0   3 120]]
**********************************************************************
classifier : SVC(kernel='linear', random_state=0)
confusion matrix :-
[[416   0   0   0]
 [  0  92   0   0]
 [  0   0 160   0]
 [  8  29  67  19]]
**********************************************************************
